// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7

using System;
using System.CodeDom.Compiler;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRClanStats.DataModel.Models
{
    // ClanStatsWeekly
    [GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class ClanStatsWeekly
    {
        public DateTime RecordDate { get; set; } // RecordDate (Primary key)
        public int Trophies { get; set; } // Trophies
        public int Donations { get; set; } // Donations
        public int ClanChestCrowns { get; set; } // ClanChestCrowns
        public int ClanChestsCompleted { get; set; } // ClanChestsCompleted
        public DateTime? ClanChestsDoneDate { get; set; } // ClanChestsDoneDate
    }
}
// </auto-generated>