// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7

using System;
using System.CodeDom.Compiler;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRClanStats.DataModel.Models
{
    // PlayerStatsWeekly
    [GeneratedCode("EF.Reverse.POCO.Generator", "2.35.0.0")]
    public class PlayerStatsWeekly
    {
        public DateTime RecordDate { get; set; } // RecordDate (Primary key)
        public int PlayerId { get; set; } // PlayerId (Primary key)
        public int Trophies { get; set; } // Trophies
        public int Donations { get; set; } // Donations
        public int DonationsReceived { get; set; } // DonationsReceived
        public int ClanChestCrowns { get; set; } // ClanChestCrowns

        // Foreign keys

        /// <summary>
        ///     Parent Player pointed by [PlayerStatsWeekly].([PlayerId]) (FK_PlayerStatsWeekly_ToPlayer)
        /// </summary>
        public virtual Player Player { get; set; } // FK_PlayerStatsWeekly_ToPlayer
    }
}
// </auto-generated>