// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRClanStats.DataModel
{

    public class ClanStat
    {
        public System.DateTime RecordDate { get; set; }
        public int Trophies { get; set; }
        public int Donations { get; set; }
        public int ClanChestCrowns { get; set; }
        public int ClanChestsCompleted { get; set; }
        public int ClanMemberCount { get; set; }
    }

}
// </auto-generated>
