// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRClanStats.DataModel
{

    public class ClanStatMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ClanStat>
    {
        public ClanStatMap()
            : this("dbo")
        {
        }

        public ClanStatMap(string schema)
        {
            ToTable("ClanStats", schema);
            HasKey(x => x.RecordDate);

            Property(x => x.RecordDate).HasColumnName(@"RecordDate").HasColumnType("datetime2").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Trophies).HasColumnName(@"Trophies").HasColumnType("int").IsRequired();
            Property(x => x.Donations).HasColumnName(@"Donations").HasColumnType("int").IsRequired();
            Property(x => x.ClanChestCrowns).HasColumnName(@"ClanChestCrowns").HasColumnType("int").IsRequired();
            Property(x => x.ClanChestsCompleted).HasColumnName(@"ClanChestsCompleted").HasColumnType("int").IsRequired();
            Property(x => x.ClanMemberCount).HasColumnName(@"ClanMemberCount").HasColumnType("int").IsRequired();
        }
    }

}
// </auto-generated>
