// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRClanStats.DataModel
{

    public class ClanStatsWeeklyMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ClanStatsWeekly>
    {
        public ClanStatsWeeklyMap()
            : this("dbo")
        {
        }

        public ClanStatsWeeklyMap(string schema)
        {
            ToTable("ClanStatsWeekly", schema);
            HasKey(x => x.RecordDate);

            Property(x => x.RecordDate).HasColumnName(@"RecordDate").HasColumnType("datetime2").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.TotalTrophies).HasColumnName(@"TotalTrophies").HasColumnType("int").IsRequired();
            Property(x => x.TotalDonations).HasColumnName(@"TotalDonations").HasColumnType("int").IsRequired();
            Property(x => x.ClanMemberCount).HasColumnName(@"ClanMemberCount").HasColumnType("int").IsRequired();
            Property(x => x.ClanChestCrownsCount).HasColumnName(@"ClanChestCrownsCount").HasColumnType("int").IsRequired();
            Property(x => x.ClanChestsCompletedCount).HasColumnName(@"ClanChestsCompletedCount").HasColumnType("int").IsRequired();
            Property(x => x.ClanChestNonParticipationCount).HasColumnName(@"ClanChestNonParticipationCount").HasColumnType("int").IsRequired();
            Property(x => x.ClanChestFullParticipationCount).HasColumnName(@"ClanChestFullParticipationCount").HasColumnType("int").IsRequired();
            Property(x => x.TopDonationsPlayer).HasColumnName(@"TopDonationsPlayer").HasColumnType("int").IsRequired();
            Property(x => x.TopCrownsPlayer).HasColumnName(@"TopCrownsPlayer").HasColumnType("int").IsRequired();

            HasRequired(a => a.Player_TopCrownsPlayer).WithMany(b => b.ClanStatsWeeklies_TopCrownsPlayer).HasForeignKey(c => c.TopCrownsPlayer).WillCascadeOnDelete(false);
            HasRequired(a => a.Player_TopDonationsPlayer).WithMany(b => b.ClanStatsWeeklies_TopDonationsPlayer).HasForeignKey(c => c.TopDonationsPlayer).WillCascadeOnDelete(false);
        }
    }

}
// </auto-generated>
