// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRClanStats.DataModel
{

    public class PlayerRoleMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PlayerRole>
    {
        public PlayerRoleMap()
            : this("dbo")
        {
        }

        public PlayerRoleMap(string schema)
        {
            ToTable("PlayerRole", schema);
            HasKey(x => x.PlayerRoleId);

            Property(x => x.PlayerRoleId).HasColumnName(@"PlayerRoleId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.RoleName).HasColumnName(@"RoleName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
        }
    }

}
// </auto-generated>
