// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRClanStats.DataModel
{

    public class PlayerStatsWeeklyMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PlayerStatsWeekly>
    {
        public PlayerStatsWeeklyMap()
            : this("dbo")
        {
        }

        public PlayerStatsWeeklyMap(string schema)
        {
            ToTable("PlayerStatsWeekly", schema);
            HasKey(x => new { x.RecordDate, x.PlayerId });

            Property(x => x.RecordDate).HasColumnName(@"RecordDate").HasColumnType("datetime2").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PlayerId).HasColumnName(@"PlayerId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Trophies).HasColumnName(@"Trophies").HasColumnType("int").IsRequired();
            Property(x => x.DonationsCount).HasColumnName(@"DonationsCount").HasColumnType("int").IsRequired();
            Property(x => x.DonationsReceivedCount).HasColumnName(@"DonationsReceivedCount").HasColumnType("int").IsRequired();
            Property(x => x.ClanChestCrownsCount).HasColumnName(@"ClanChestCrownsCount").HasColumnType("int").IsOptional();
            Property(x => x.IsClanChestEligible).HasColumnName(@"IsClanChestEligible").HasColumnType("bit").IsRequired();
            Property(x => x.C1V1MatchCount).HasColumnName(@"1v1MatchCount").HasColumnType("int").IsOptional();
            Property(x => x.C2V2MatchCount).HasColumnName(@"2v2MatchCount").HasColumnType("int").IsOptional();
            Property(x => x.FriendlyMatchCount).HasColumnName(@"FriendlyMatchCount").HasColumnType("int").IsOptional();
            Property(x => x.TournamentMatch).HasColumnName(@"TournamentMatch").HasColumnType("int").IsOptional();
            Property(x => x.ChallengeMatchCount).HasColumnName(@"ChallengeMatchCount").HasColumnType("int").IsOptional();
            Property(x => x.SharedCount).HasColumnName(@"SharedCount").HasColumnType("int").IsOptional();
            Property(x => x.ChatLogPostCount).HasColumnName(@"ChatLogPostCount").HasColumnType("int").IsOptional();
            Property(x => x.PlayerRoleId).HasColumnName(@"PlayerRoleId").HasColumnType("int").IsRequired();

            HasRequired(a => a.Player).WithMany(b => b.PlayerStatsWeeklies).HasForeignKey(c => c.PlayerId).WillCascadeOnDelete(false);
            HasRequired(a => a.PlayerRole).WithMany(b => b.PlayerStatsWeeklies).HasForeignKey(c => c.PlayerRoleId).WillCascadeOnDelete(false);
        }
    }

}
// </auto-generated>
