// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRClanStats.DataModel
{

    public class PlayerMap : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Player>
    {
        public PlayerMap()
            : this("dbo")
        {
        }

        public PlayerMap(string schema)
        {
            ToTable("Player", schema);
            HasKey(x => x.PlayerId);

            Property(x => x.PlayerId).HasColumnName(@"PlayerId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Tag).HasColumnName(@"Tag").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(10);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.FormerName).HasColumnName(@"FormerName").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
            Property(x => x.JoinCount).HasColumnName(@"JoinCount").HasColumnType("int").IsRequired();
            Property(x => x.IsCurrentMember).HasColumnName(@"IsCurrentMember").HasColumnType("bit").IsRequired();
            Property(x => x.Notes).HasColumnName(@"Notes").HasColumnType("text").IsOptional().IsUnicode(false).HasMaxLength(2147483647);
        }
    }

}
// </auto-generated>
