// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRClanStats.DataModel
{

    public class PlayerStatsWeekly
    {
        public System.DateTime RecordDate { get; set; }
        public int PlayerId { get; set; }
        public int Trophies { get; set; }
        public int DonationsCount { get; set; }
        public int DonationsReceivedCount { get; set; }
        public int? ClanChestCrownsCount { get; set; }
        public int PlayerRoleId { get; set; }


        public virtual Player Player { get; set; }

        public virtual PlayerRole PlayerRole { get; set; }
    }

}
// </auto-generated>
