// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRClanStats.DataModel
{

    public class PlayerRole
    {
        public int PlayerRoleId { get; set; }
        public string RoleName { get; set; }

        public virtual System.Collections.Generic.ICollection<PlayerStat> PlayerStats { get; set; } = new System.Collections.Generic.List<PlayerStat>();
        public virtual System.Collections.Generic.ICollection<PlayerStatsWeekly> PlayerStatsWeeklies { get; set; } = new System.Collections.Generic.List<PlayerStatsWeekly>();
    }

}
// </auto-generated>
