// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CRClanStats.DataModel
{

    public class Player
    {
        public int PlayerId { get; set; }
        public string Tag { get; set; }
        public string Name { get; set; }
        public string FormerName { get; set; }
        public int JoinCount { get; set; } = 1;
        public bool IsCurrentMember { get; set; } = true;
        public string Notes { get; set; }

        public virtual System.Collections.Generic.ICollection<ClanStatsWeekly> ClanStatsWeeklies_TopCrownsPlayer { get; set; } = new System.Collections.Generic.List<ClanStatsWeekly>();
        public virtual System.Collections.Generic.ICollection<ClanStatsWeekly> ClanStatsWeeklies_TopDonationsPlayer { get; set; } = new System.Collections.Generic.List<ClanStatsWeekly>();
        public virtual System.Collections.Generic.ICollection<PlayerStat> PlayerStats { get; set; } = new System.Collections.Generic.List<PlayerStat>();
        public virtual System.Collections.Generic.ICollection<PlayerStatsWeekly> PlayerStatsWeeklies { get; set; } = new System.Collections.Generic.List<PlayerStatsWeekly>();
    }

}
// </auto-generated>
